spring:
  application:
    name: medical-care-scheduler-backend
  datasource:
    url: jdbc:mariadb://localhost:3306/medical_scheduler
    username: root
    password: lucky369@yahoo
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 8080
